### ISSUE TITLE
Number of likes on posts and comments

### ISSUE THREAD

**Issue by sydneynicolla** [Social-Design-Lab/vaping#14]
Reposting because it was marked as resolved but the likes on posts and comments are still showing up as inconsistent (from our end).

Please hard code the "likes" for the different studies as follows so that across conditions, all experimental posts and comments appear to have been "liked" the same amount of times.

Vaping Study (ALID)
Posts: 11 likes each
Comments: 0 likes for all comments

Drinking Perceptions Study (SNID)
Posts: 12 likes each
comments: 1 like for each comment

Eating study (RVID)
Posts: 13 likes each
Comments: n/a (There are no comments for the posts for this study)

**Comment by chenchenmao96** [comment]
everything is updated now . please take a look and let me know if there is any questions

**Comment by sydneynicolla** [comment]
<img width="397" alt="Screen Shot 2022-09-27 at 11 33 46 AM" src="https://user-images.githubusercontent.com/113939586/192570629-d691f16f-ba49-4dc0-9900-321523341dc9.png">

Thank you. Many of the issues look resolved now, but there are a couple missing updates. 

Each comment on this post should only have 1 like (in all conditions). I will keep reviewing and check with the team to make sure there are no other issues.

**Comment by sydneynicolla** [comment]
I looked through and found the following posts in need of correction:
ALID3B (should be zero likes on all comments)
SNID1A, SNID2A, SNID3A (should be 1 like on all comments)

**Comment by chenchenmao96** [comment]
the problem should be solved

**Comment by sydneynicolla** [comment]
All the SNID posts are correct now. ALID3B is still showing 2 likes on the first comment. 

Thank you for all your help!

<img width="381" alt="Screen Shot 2022-10-04 at 8 18 48 AM" src="https://user-images.githubusercontent.com/113939586/193817367-c21ddee7-d0ec-4e36-ae4c-6152bd8fdebe.png">

**Comment by chenchenmao96** [comment]
fixed
